export const OPEN_ORDER_INFO_MODAL = 'OPEN_ORDER_INFO_MODAL';
export const CLOSE_ORDER_INFO_MODAL = 'CLOSE_ORDER_INFO_MODAL';
export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST'
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS'
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED'
