export const CHANGE_BUN: 'CHANGE_BUN' = 'CHANGE_BUN';
export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const SORT_CARD: 'SORT_CARD' = 'SORT_CARD';
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
