export const SET_ACTIVE_ORDERS: 'SET_ACTIVE_ORDERS' = 'SET_ACTIVE_ORDERS';
export const SET_DONE_ORDERS: 'SET_DONE_ORDERS' = 'SET_DONE_ORDERS';
export const SELECT_ORDER: 'SELECT_ORDER' = 'SELECT_ORDER';
export const UNSELECT_ORDER: 'UNSELECT_ORDER' = 'UNSELECT_ORDER';
