export const FORGOT_PASSWORD_FORM_SUBMIT: 'FORGOT_PASSWORD_FORM_SUBMIT' = 'FORGOT_PASSWORD_FORM_SUBMIT';
export const FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS: 'FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS' = 'FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS';
export const FORGOT_PASSWORD_FORM_SUBMIT_FAILED: 'FORGOT_PASSWORD_FORM_SUBMIT_FAILED' = 'FORGOT_PASSWORD_FORM_SUBMIT_FAILED';
export const RESET_PASSWORD_FORM_SUBMIT: 'RESET_PASSWORD_FORM_SUBMIT' = 'RESET_PASSWORD_FORM_SUBMIT';
export const RESET_PASSWORD_FORM_SUBMIT_SUCCESS: 'RESET_PASSWORD_FORM_SUBMIT_SUCCESS' = 'RESET_PASSWORD_FORM_SUBMIT_SUCCESS';
export const RESET_PASSWORD_FORM_SUBMIT_FAILED: 'RESET_PASSWORD_FORM_SUBMIT_FAILED' = 'RESET_PASSWORD_FORM_SUBMIT_FAILED';
