export const EDIT_PROFILE_FORM_SUBMIT: 'EDIT_PROFILE_FORM_SUBMIT' = 'EDIT_PROFILE_FORM_SUBMIT';
export const EDIT_PROFILE_FORM_SUBMIT_SUCCESS: 'EDIT_PROFILE_FORM_SUBMIT_SUCCESS' = 'EDIT_PROFILE_FORM_SUBMIT_SUCCESS';
export const EDIT_PROFILE_FORM_SUBMIT_FAILED: 'EDIT_PROFILE_FORM_SUBMIT_FAILED' = 'EDIT_PROFILE_FORM_SUBMIT_FAILED';
export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
